name: Checks
on:
  workflow_call:

jobs:
  run-checks:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Composer install
        uses: php-actions/composer@v6 # or alternative dependency management
      - name: Phpstan install
        uses: php-actions/phpstan@v3
      - name: Phpstan run
        run: composer phpstan