name: Checks
on:
  workflow_call:

jobs:
  run-checks:
    runs-on: ubuntu-latest
    steps:
      - name: Setup PHP Action
        uses: shivammathur/setup-php@2.31.1
      - name: Checkout
        uses: actions/checkout@v4
      - name: Composer install
        uses: php-actions/composer@v6
      - name: Phpstan install
        uses: php-actions/phpstan@v3
      - name: Phpstan run
        run: composer phpstan
      - name: Easy coding standards run
        run: composer ecs
      - name: PHP Mess Detector run
        uses: php-actions/phpmd@v1
        with:
          php_version: 8.3
          path: app/
          ruleset: ruleset.xml
          output: github