name: Checks
on:
  workflow_call:

jobs:
  run-checks:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Composer install
        uses: php-actions/composer@v6
      - run: |
          pwd
          ls -a
      - name: Phpstan install
        uses: php-actions/phpstan@v3
        with:
          configuration: $GITHUB_WORKSPACE/phpstan.neon
          path: $GITHUB_WORKSPACE
      - name: Phpstan run
        run: composer phpstan